excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Melomind.iOS-V2Tests
  - Melomind.iOS-V2/Ressources/Generated
disabled_rules: # rule identifiers to exclude from running
## Explicitly disabled rules
  - empty_parentheses_with_trailing_closure
  - opening_brace
  - closure_parameter_position
  - colon
## Fixed
#  - identifier_name
#  - switch_case_alignment
# - legacy_constructor
# - large_tuple
# - vertical_whitespace
# - trailing_whitespace
# - trailing_newline
# - leading_whitespace
# - trailing_semicolon
# - return_arrow_whitespace
# - trailing_comma
# - redundant_optional_initialization
# - redundant_discardable_let
# - void_return
# - closing_brace
# - multiple_closures_with_trailing_closure
# - unused_closure_parameter
# - unused_optional_binding
# - vertical_parameter_alignment
# - empty_enum_arguments
# - control_statement
# - for_where
## Rules not fixed yet
  - cyclomatic_complexity
  - todo
  - file_length
  - class_delegate_protocol
  - function_body_length
  - line_length
  - comma
  - mark
  - statement_position
  - duplicate_imports
  - redundant_string_enum_value
  - implicit_getter
  - private_over_fileprivate
  - unused_setter_value
  - deployment_target
## error rules not fixed yet
  - force_cast
  - type_name
  - force_try
  - type_body_length
## Some rules custom
identifier_name:
  min_length: 1
  max_length: 40
line_length:
  warning: 80
  ignores_comments: true
file_length:
  warning: 500
