# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Create a xcframework"
  lane :generate_xcframework do
    sh "bash ../generate_xcframework.sh"
#     create_xcframework(
#     workspace: './MyBrainTechnologiesSDK.xcodeproj/project.xcworkspace',
#     scheme: 'MyBrainTechnologiesSDK',
#     product_name: 'MyBrainTechnologiesSDK', # optional if scheme doesnt match the name of your framework
#     destinations: ['iOS'],
#     xcframework_output_directory: './build'
# )
  end
end
